=== BrentBaccala/hoffman/tablebase.dtd
<!ELEMENT tablebase (move-restriction*, piece+, futurebase*, prune*, generated-by?)>
<!ELEMENT move-restriction EMPTY>
<!ELEMENT piece EMPTY>
<!ELEMENT futurebase EMPTY>
<!ELEMENT prune EMPTY>

<!ELEMENT generated-by (program, time, host)>
<!ELEMENT program EMPTY>
<!ELEMENT time EMPTY>
<!ELEMENT host EMPTY>

<!ATTLIST tablebase
	offset	CDATA		#IMPLIED
	format	(fourbyte)	#IMPLIED
	index	(naive|simple)	#IMPLIED>

<!ATTLIST piece
	color	(white|black)	#REQUIRED
	type	(king|queen|rook|bishop|knight|pawn)	#REQUIRED
	location CDATA		#IMPLIED>
<!ATTLIST futurebase
	filename CDATA		#REQUIRED
	type	(normal|capture|promotion|promotion-capture)	#REQUIRED
	colors	(invert)	#IMPLIED>
<!ATTLIST prune
	color	(white|black)	#REQUIRED
	move	CDATA		#REQUIRED
	type	(concede|discard)	#REQUIRED>

<!ATTLIST move-restriction
	color	(white|black)	#REQUIRED
	type	(concede|discard)	#REQUIRED>

<!ATTLIST generating-program
	name	CDATA		#REQUIRED
	version	CDATA		#REQUIRED>
<!ATTLIST generating-time
	time	CDATA		#REQUIRED>
<!ATTLIST generating-host
	fqdn	CDATA		#REQUIRED>

=== BrentBaccala/hoffman/xml/kpkp_nalimov.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- Created by genctlfile.pl -->
<!-- Modified by hand to use Nalimov instead of Hoffman futurebase -->

<tablebase>
   <dtm/>
   <piece color="white" type="king"/>
   <piece color="black" type="king"/>
   <piece color="white" type="pawn"/>
   <piece color="black" type="pawn"/>
   <futurebase filename="kpk.nbw.emd"/>
   <futurebase filename="kqkp.nbw.emd"/>
   <futurebase filename="krkp.nbw.emd"/>
   <futurebase filename="kbkp.nbw.emd"/>
   <futurebase filename="knkp.nbw.emd"/>
   <output filename="kpkp_nalimov.htb"/>
</tablebase>

=== BrentBaccala/hoffman/xml/kpk-4+.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">

<tablebase>
   <dtm/>
   <piece color="white" type="king"/>
   <piece color="black" type="king"/>
   <piece color="white" type="pawn" location="a4 a5 a6 a7 b4 b5 b6 b7 c4 c5 c6 c7 d4 d5 d6 d7 e4 e5 e6 e7 f4 f5 f6 f7 g4 g5 g6 g7 h4 h5 h6 h7"/>
   <futurebase filename="kk.htb"/>
   <futurebase filename="kqk.htb"/>
   <futurebase filename="krk.htb"/>
   <futurebase filename="kbk.htb"/>
   <futurebase filename="knk.htb"/>
   <output filename ="kpk-4+.htb"/>
</tablebase>

=== BrentBaccala/hoffman/xml/ivan11.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- submitted by Ivan Konobeev on 11/12/13 -->
<!-- generating with "-g -v" reported internal inconsistencies -->
<!-- fixed in 1.808 -->

<tablebase>


<prune-enable color="black" type="concede"/>
<prune-enable color="black" type="discard"/>

<piece color="white" type="king"/>
<piece color="white" type="rook"/>
<piece color="black" type="king"/>
<piece color="black" type="rook"/>
<piece color="black" type="pawn" location="d4+"/>

<futurebase filename="kqrkr.htb" colors="invert"/> <!-- P=q-->
<futurebase filename="krpk.htb" colors="invert"/> <!-- kxR rxR pxR-->
<futurebase filename="krkr.htb"/> <!-- Kxp Rxp-->
<futurebase filename="krkp.htb"/> <!-- Kxr Rxr-->

<prune color="black" move="PxR=?" type="concede"/>
<prune color="black" move="P=[RNB]" type="discard"/>

<output filename ="ivan11.htb"/>
</tablebase>

=== BrentBaccala/hoffman/xml/maroczy-marshall.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- from Maroczy-Marshall Monaco 1903 -->
<!-- this is a drawing analysis for white -->

<tablebase>
   <prune-enable color="white" type="discard"/>
   <prune-enable color="black" type="concede"/>
   <dtm/>
   <piece color="white" type="king"/>
   <piece color="black" type="king"/>
   <piece color="white" type="pawn" location="a2+"/>
   <piece color="white" type="pawn" location="b3+"/>
   <piece color="white" type="pawn" location="g3+"/>
   <piece color="white" type="pawn" location="h2+"/>
   <piece color="black" type="pawn" location="c6+"/>
   <piece color="black" type="pawn" location="d5+"/>
   <piece color="black" type="pawn" location="f7+"/>
   <piece color="black" type="pawn" location="g7+"/>
   <piece color="white" type="knight"/>
   <piece color="black" type="knight"/>
   <futurebase filename="kpkp.htb"/>
   <prune color="white" type="discard" move="P*=?"/>
   <prune color="black" type="concede" move="P*=?"/>
</tablebase>

=== BrentBaccala/hoffman/xml/fortress1.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">

<tablebase>
   <prune-enable color="white" type="discard"/>
   <!-- The entire analysis is done with black concede -->
   <!--   but we don't actually need it for this part. -->
   <!-- <prune-enable color="black" type="concede"/> -->

   <dtm/>
   <piece color="white" type="king" location="e1 f1 g1 h1 e2 f2 g2 h2 e3 f3 g3 h3"/>
   <piece color="black" type="king"/>
   <piece color="white" type="rook" location="e3 g3"/>
   <piece color="black" type="queen"/>
   <piece color="white" type="pawn" location="f2"/>

   <!-- if black takes the white pawn -->
   <futurebase filename="kqkr.htb" colors="invert"/>
   <!-- if black takes the white rook -->
   <futurebase filename="kqkp.htb" colors="invert"/>
   <!-- if white takes the black queen -->
   <futurebase filename="krpk.htb"/>

   <prune color="white" move="Pf3" type="discard"/>
   <prune color="white" move="Pf4" type="discard"/>
   <prune color="white" move="R*" type="discard"/>
   <prune color="white" move="K*" type="discard"/>

   <output filename="fortress1.htb"/>
</tablebase>

=== BrentBaccala/hoffman/xml/fine67.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- Diagram 67 from Rubin Fine's "Basic Chess Endings" -->

<tablebase>
   <prune-enable color="white" type="concede"/>
   <prune-enable color="black" type="concede"/>
   <dtm/>
   <piece color="white" type="king"/>
   <piece color="black" type="king"/>
   <piece color="white" type="pawn" location="b3+"/>
   <piece color="black" type="pawn" location="b5+"/>
   <piece color="white" type="pawn" location="c2+"/>
   <piece color="black" type="pawn" location="c7+"/>
   <piece color="white" type="pawn" location="d3+"/>
   <piece color="black" type="pawn" location="d5+"/>
   <futurebase filename="kpk.htb"/>
   <futurebase filename="kpk.htb" colors="invert"/>
   <prune color="white" type="concede" move="P=?"/>
   <prune color="black" type="concede" move="P=?"/>
</tablebase>

=== BrentBaccala/hoffman/xml/krppkrp.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- FEN: 8/8/4r3/3k1K2/3p3P/8/6P1/7R b - -   -->
<!-- We want to know if black can draw or not; analysys by FinalGen shows that the only chance for black is move Re8. But FinalGen cannot handle with move Re8 and marks it as "White wins or Draw" -->

<tablebase>
   <prune-enable color="white" type="concede"/>
   <prune-enable color="black" type="concede"/>
   <prune-enable color="white" type="discard"/>
   <prune-enable color="black" type="discard"/>

   <piece color="white" type="king" location="b1 b2 b3 b4 b5 c1 c2 c3 c4 c5 c6 d1 d2 d3 d4 d5 d6 d7 e1 e2 e3 e4 e5 e6 e7 e8 f1 f2 f3 f4 f5 f6 f7 f8 g3 g4 g5 g6 g7 g8 h3 h4 h5 h6 h7 h8"/>
   <piece color="white" type="rook"/>
   <piece color="white" type="pawn" location="g2+"/>
   <piece color="white" type="pawn" location="h4+"/>
   <piece color="black" type="king" location="b1 b2 b3 b4 b5 c1 c2 c3 c4 c5 c6 d1 d2 d3 d4 d5 d6 d7 e1 e2 e3 e4 e5 e6 e7 e8 f1 f2 f3 f4 f5 f6 f7 f8 g3 g4 g5 g6 g7 g8 h3 h4 h5 h6 h7 h8"/>
   <piece color="black" type="rook"/>
   <piece color="black" type="pawn" location="d4+"/>
   
   <futurebase filename="kqrpkrp_.htb"/>  <!-- P=Q; isn't a win for white yet, we need to be sure that white queen can't be captured immediately-->
   <futurebase filename="krppkqr_.htb"/> <!-- P=q; isn't a win for black yet, we need to be sure that black queen can't be captured immediately-->
   <futurebase filename="krppkr_.htb"/> <!-- Kxp Rxp-->
   <futurebase filename="krppkp_.htb"/> <!-- Kxr Rxr-->
   <futurebase filename="kppkrp_.htb"/> <!-- kxR rxR; move pxR (as pxR=q;) should be conceded so black pawn continues to be at "d" line only-->
   <futurebase filename="krpkrp_.htb"/> <!-- kxP rxP-->

   <prune color="white" move="PxR*" type="concede"/>
   <prune color="black" move="PxR*" type="concede"/>
   <prune color="white" move="P=[RNB]" type="discard"/>
   <prune color="black" move="P=[RNB]" type="discard"/>

   <prune color="white" move="Ka?" type="discard"/>
   <prune color="white" move="Kb?" type="discard"/>
   <prune color="white" move="Kc?" type="discard"/>
   <prune color="white" move="Kd?" type="discard"/>
   <prune color="white" move="Kg?" type="discard"/>
   <prune color="white" move="Kh?" type="discard"/>

   <prune color="black" move="Ka?" type="discard"/>
   <prune color="black" move="Kb?" type="discard"/>
   <prune color="black" move="Kc?" type="discard"/>
   <prune color="black" move="Kd?" type="discard"/>
   <prune color="black" move="Kg?" type="discard"/>
   <prune color="black" move="Kh?" type="discard"/>
   
   <output filename ="krppkrp_.htb"/>
</tablebase>

=== BrentBaccala/hoffman/xml/r814.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- Created by genctlfile.pl -->

<tablebase>
   <dtm bits="4"/>
   <piece color="white" type="king"/>
   <piece color="black" type="king"/>
   <piece color="white" type="pawn"/>
   <futurebase filename="kk.htb"/>
   <futurebase filename="kqk.htb"/>
   <futurebase filename="krk.htb"/>
   <futurebase filename="kbk.htb"/>
   <futurebase filename="knk.htb"/>
   <output filename ="r814.htb"/>
</tablebase>
