=== BrentBaccala/hoffman/tablebase.dtd
<!ELEMENT tablebase (move-restriction*, piece+, futurebase*, prune*, generated-by?)>
<!ELEMENT move-restriction EMPTY>
<!ELEMENT piece EMPTY>
<!ELEMENT futurebase EMPTY>
<!ELEMENT prune EMPTY>

<!ELEMENT generated-by (program, time, host)>
<!ELEMENT program EMPTY>
<!ELEMENT time EMPTY>
<!ELEMENT host EMPTY>

<!ATTLIST tablebase
	offset	CDATA		#IMPLIED
	format	(fourbyte)	#IMPLIED
	index	(naive|simple)	#IMPLIED>

<!ATTLIST piece
	color	(white|black)	#REQUIRED
	type	(king|queen|rook|bishop|knight|pawn)	#REQUIRED
	location CDATA		#IMPLIED>
<!ATTLIST futurebase
	filename CDATA		#REQUIRED
	type	(normal|capture|promotion|promotion-capture)	#REQUIRED
	colors	(invert)	#IMPLIED>
<!ATTLIST prune
	color	(white|black)	#REQUIRED
	move	CDATA		#REQUIRED
	type	(concede|discard)	#REQUIRED>

<!ATTLIST move-restriction
	color	(white|black)	#REQUIRED
	type	(concede|discard)	#REQUIRED>

<!ATTLIST generating-program
	name	CDATA		#REQUIRED
	version	CDATA		#REQUIRED>
<!ATTLIST generating-time
	time	CDATA		#REQUIRED>
<!ATTLIST generating-host
	fqdn	CDATA		#REQUIRED>

=== BrentBaccala/hoffman/xml/kpkp_syzygy.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- Created by genctlfile.pl -->
<!-- Modified by hand to use Syzygy instead of Hoffman futurebase -->

<tablebase>
   <dtc/>
   <piece color="white" type="king"/>
   <piece color="black" type="king"/>
   <piece color="white" type="pawn"/>
   <piece color="black" type="pawn"/>
   <futurebase filename="KPvK.rtbw"/>
   <futurebase filename="KQvKP.rtbw"/>
   <futurebase filename="KRvKP.rtbw"/>
   <futurebase filename="KBvKP.rtbw"/>
   <futurebase filename="KNvKP.rtbw"/>
   <output filename="kpkp_syzygy.htb"/>
</tablebase>

=== BrentBaccala/hoffman/xml/r984b.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- NEGATIVE BUILD -->
<!-- This test case is expected to fail, due to multiple futuremoves -->

<tablebase>
   <dtm/>
   <piece color="white" type="king"/>
   <piece color="black" type="king"/>
   <piece color="white" type="queen"/>
   <piece color="black" type="queen"/>
   <futurebase filename="kqk.htb"/>
   <futurebase filename="kqk.htb"/>
   <futurebase filename="kqk.htb"/>
   <output filename="r984b.htb"/>
</tablebase>

=== BrentBaccala/hoffman/xml/fine67a.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- Diagram 67 from Rubin Fine's "Basic Chess Endings" -->
<!-- Problem position 8/2p5/3k4/1p1p1K2/8/1P1P4/2P5/8 w -->

<tablebase>
   <prune-enable color="white" type="discard"/>
   <prune-enable color="black" type="concede"/>
   <dtm/>
   <piece color="white" type="king"/>
   <piece color="white" type="pawn" location="b3+"/>
   <piece color="white" type="pawn" location="c2+"/>
   <piece color="white" type="pawn" location="d3+"/>
   <piece color="black" type="king"/>
   <piece color="black" type="pawn" location="b5+"/>
   <piece color="black" type="pawn" location="c7+"/>
   <piece color="black" type="pawn" location="d5+"/>
   <futurebase filename="kpkp.htb"/>
   <futurebase filename="kppk.htb"/>
   <futurebase filename="kppk.htb" colors="invert"/>
   <futurebase filename="kqkp.htb"/>
   <futurebase filename="kqpk.htb"/>
   <prune color="white" type="discard" move="P=Q" pawngen-condition="grep(/Q/,@white_pieces)==1"/>
   <prune color="white" type="discard" move="P=[RNB]"/>
   <prune color="black" type="concede" move="P*=?"/>
   <prune color="black" type="concede" move="?xQ"/>
   <prune color="black" type="concede" move="?xP" pawngen-condition="grep(/Q/,@white_pieces)==0 and $#white_pawns==0"/>
</tablebase>

=== BrentBaccala/hoffman/xml/carlsen_anand_2014.xml
<?xml version="1.0"?>
<!DOCTYPE tablebase SYSTEM "http://www.freesoft.org/software/hoffman/tablebase.dtd">
<!-- Carlsen-Anand 2014 World Championship Match Game 7 -->
<!-- Problem position 3k4/ppp5/8/2p1R3/6r1/6N1/1PP2K2/8 b - - 0 33 -->

<tablebase>
   <prune-enable color="white" type="concede"/>
   <prune-enable color="black" type="concede"/>

   <piece color="white" type="king"/>
   <piece color="black" type="king"/>
   <piece color="white" type="rook"/>
   <piece color="white" type="knight"/>
   <piece color="black" type="rook"/>
   <!-- <pawngen white-pawn-locations="b2 c2" black-pawn-locations="a7 b7 c7 c5" white-pawns-required="2" black-pawns-required="4"/> -->

   <prune color="white" move="P*=*" type="concede"/>
   <prune color="black" move="P*=*" type="concede"/>

   <futurebase filename="krnkr.htb"/>
   <futurebase filename="krnkp.htb"/>
   <futurebase filename="krkr.htb"/>
   <futurebase filename="krkp.htb"/>
   <futurebase filename="krkn.htb" colors="invert"/>
   <futurebase filename="knkp.htb"/>
   <futurebase filename="krpk.htb" colors="invert"/>
   <futurebase filename="kppk.htb" colors="invert"/>

   <!-- <output filename="carlsen_anand_2014.htb"/> -->
</tablebase>
